KIWI-1256-QA Added Authorisation tests
govuk-one-login/ipv-cri-bav-api pull request #18
Opened 2023-10-30 15:38 UTC by shenry99

The creation of Authoristaion Happy and Unhappy Path tests for BAV API

Added Happy and Unhappy path tests to test the /authorisation end point

### Issue tracking

- [KIWI-1256](https://govukverify.atlassian.net/browse/KIWI-1256)

## Checklists

### PII logging
- [ ] Verified that no PII data is being logged

### Environment variables or secrets
- [ ] No environment variables or secrets were added or changed

### Other considerations
N/A

2023-10-30 16:05 UTC, Caitlin-cooling commented on src/tests/api/BavHappyPath.test.ts
> +    it.skip("E2E Happy Path Journey - Well Known", async () => {
Why do we need to skip this? I thought the well known endpoint was finished

2023-10-30 16:05 UTC, Caitlin-cooling commented on src/tests/api/BavUnhappyPath.test.ts
> +	it.skip("Incorrect session state", async () => {
And this? I would have hoped it would work

2023-10-31 09:15 UTC, Z-Mohamoud requested changes

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +    it.skip("E2E BAV End Points Happy Path Journey", async () => {
Why has the /session validation been removed? 

We should not be removing any existing logic and adding to it instead. 

Please re-add the authSessionState validation that was part of the /session endpoint PR and then you should kick off your logic to hit the /authorization endpoint and then validate the authSessionState again

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
>          const sqsMessage = await getSqsEventList("txma/", sessionId, 1);
Why are we still only validating 1 TxMA message? 

The logic in place prior to this PR was hitting the session endpoint and validating **1** TxMA event. 

If you're adding an additional endpoint which results in an additional TxMA event we should be validating that we get 2 in total and both are formatted correctly.

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +    it.skip("E2E BAV End Points Happy Path Journey", async () => {
Please add your logic to a new test. 

I understand we can't test /authorization endpoint in completion due to the /verifyAccount endpoint not being in place. 

But we should not be adding this logic to the only BAV test we have working and marking it as skipped

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavUnhappyPath.test.ts
> +    it.skip("E2E Unhappy Path Journey - Invalid Request", async () => {
Why is this being skipped?

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavUnhappyPath.test.ts
> +    it.skip("E2E Unhappy Path Journey - Invalid ClientID", async () => {
Again, why is this being skipped?

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/api/BavUnhappyPath.test.ts
> +	it.skip("Incorrect session state", async () => {
Another skipped test, should this not be working with what we currently have deployed?

2023-10-31 09:15 UTC, Z-Mohamoud commented on src/tests/data/BAV_CRI_AUTH_CODE_ISSUED_SCHEMA.json
> +{
Schema looks good, but if we're only validating 1 of the 2 TxMA events returned (BAV_CRI_START and BAV_CRI_AUTH_CODE_ISSUED) are you sure this schema is being used?

2023-10-31 10:47 UTC, Caitlin-cooling commented on src/tests/api/BavHappyPath.test.ts
> +    it.skip("Happy Path /authorisation endpoint - Repeated request made", async () => {
How come this is still skipped?

2023-10-31 11:54 UTC, Z-Mohamoud requested changes

2023-10-31 11:54 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +describe("Test BAV End Points", () => {
Can we have all these tests under 1 description please, sharing the same beforeEach step as this is a pre-requisite for all happy path tests and differentiate in the it statement please? 

e.g. 

- Both tests can be under the same description

`describe("BAV CRI Happy Path", () => {`

- The beforeEach logic can stay the same 
- Differentiate between tests in the it step 
/session: `    it("BAV CRI /session Happy Path", async () => {`
/authorization: `    it("BAV CRI /authorization Happy Path", async () => {`

2023-11-01 09:45 UTC, closed without merging

2023-11-01 09:46 UTC, shenry99 commented
Closing so that branch can be merged into Dev KIWI-1256 branch.