Kiwi 1258 qa
govuk-one-login/ipv-cri-bav-api pull request #26
Opened 2023-11-10 17:33 UTC by jackmardell

## Proposed changes

### What changed
Implemented the /userinfo endpoint happy and unhappy test cases.

### Issue tracking

- [KIWI-1258](https://govukverify.atlassian.net/browse/KIWI-1258)

## Checklists

### PII logging

- [x] Verified that no PII data is being logged

### Environment variables or secrets

- [x] No environment variables or secrets were added or changed

### Other considerations
- x ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-11-13 10:16 UTC, Z-Mohamoud requested changes

2023-11-13 10:16 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +    it.skip("BAV CRI /userinfo Happy Path", async () => {
Can you uncomment the logic we expect to have working when all endpoints have been delivered please? 

For userinfo, we know we'll need to call Stub, session, authorization and token endpoints first.

2023-11-13 10:16 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +        // const documentSelectionResponse = await postDocumentSelection(docSelectionData, sessionId);
Can you remove this please? Looks like F2F logic - This will eventually be replaced with /verifyAccount

2023-11-13 10:16 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +        const userInfoResponse = await userInfoPost("Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImYzODA1Y2UyLWQzNjYtNDY3ZC1iYzhkLWMzMTc4MGFmNTQyYyJ9.eyJzdWIiOiIzZjUyYzczYi05OGM2LTQxZjMtOTA5Zi
This should not be hard coded, we'll get our Bearer token from the /token response

2023-11-13 10:16 UTC, Z-Mohamoud commented on src/tests/api/BavUnhappyPath.test.ts
> +        const userInfoResponse = await userInfoPost("Basic eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImYzODA1Y2UyLWQzNjYtNDY3ZC1iYzhkLWMzMTc4MGFmNTQyYyJ9.eyJzdWIiOiJhNzhjYTE2Yi1mNTQyLTQzNzgtOWNkMC1
Same comments as HappyPath tests, endpoints needed before we hit userInfo are not in place and Bearer Token is hardcoded

2023-11-13 10:16 UTC, Z-Mohamoud commented on src/tests/api/BavUnhappyPath.test.ts
> +        const userInfoResponse = await userInfoPost("Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImYzODA1Y2UyLWQzNjYtNDY3ZC1iYzhkLWMzMTc4MGFmNTQyYyJ9.eyJzdWIiOiJhNzhjYTE2Yi1mNTQyLTQzNzgtOWNkMC
Our repo is public so we should not be committing any code that contains references to Access or Bearer tokens. Please reach out to Madan and get any tokens you need to use in tests added as a GitHub secret

2023-11-13 12:36 UTC, Z-Mohamoud commented on src/tests/api/BavHappyPath.test.ts
> +        await validateJwtToken(jwtToken);
You can tidy this up a bit by passing _userInfoResponse.data['https://vocab.account.gov.uk/v1/credentialJWT'][0]_ directly into the validateJwtToken() function if this is the only place we're using the jwtToken variable

2023-11-13 12:41 UTC, Z-Mohamoud commented on src/tests/utils/ApiTestSteps.ts
> +export function validateJwtToken(jwtToken: any): void {
You're using await validateJwtToken() in your test steps but the function you're calling is not asynchronous.

2023-11-13 15:05 UTC, Z-Mohamoud approved these changes

2023-11-13 15:35 UTC, Caitlin-cooling commented on src/tests/api/BavUnhappyPath.test.ts
> +    let tokenResponse: any;
Please can we have proper types for these?

2023-11-13 15:36 UTC, Caitlin-cooling commented on src/tests/utils/ApiConstants.ts
> +
I believe these will need to be added to the `run-tests.sh` script so that the tests pass in the container?

2023-11-13 15:37 UTC, Caitlin-cooling commented on src/tests/utils/ApiTestSteps.ts
> +	// Strength Score
[nit] are these comments needed? We can see it's `strengthScore` and `validityScore` being accessed

2023-11-15 09:42 UTC, ViveakV approved these changes

2023-11-15 09:50 UTC, merged